// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request_message.proto

public final class RequestMessageProtos {
  private RequestMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Clock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 timer = 1;</code>
     */
    boolean hasTimer();
    /**
     * <code>required int32 timer = 1;</code>
     */
    int getTimer();

    /**
     * <code>required int32 pid = 2;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 2;</code>
     */
    int getPid();
  }
  /**
   * Protobuf type {@code Clock}
   */
  public  static final class Clock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Clock)
      ClockOrBuilder {
    // Use Clock.newBuilder() to construct.
    private Clock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Clock() {
      timer_ = 0;
      pid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Clock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timer_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestMessageProtos.internal_static_Clock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestMessageProtos.internal_static_Clock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestMessageProtos.Clock.class, RequestMessageProtos.Clock.Builder.class);
    }

    private int bitField0_;
    public static final int TIMER_FIELD_NUMBER = 1;
    private int timer_;
    /**
     * <code>required int32 timer = 1;</code>
     */
    public boolean hasTimer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 timer = 1;</code>
     */
    public int getTimer() {
      return timer_;
    }

    public static final int PID_FIELD_NUMBER = 2;
    private int pid_;
    /**
     * <code>required int32 pid = 2;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 pid = 2;</code>
     */
    public int getPid() {
      return pid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, timer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timer_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestMessageProtos.Clock)) {
        return super.equals(obj);
      }
      RequestMessageProtos.Clock other = (RequestMessageProtos.Clock) obj;

      boolean result = true;
      result = result && (hasTimer() == other.hasTimer());
      if (hasTimer()) {
        result = result && (getTimer()
            == other.getTimer());
      }
      result = result && (hasPid() == other.hasPid());
      if (hasPid()) {
        result = result && (getPid()
            == other.getPid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTimer()) {
        hash = (37 * hash) + TIMER_FIELD_NUMBER;
        hash = (53 * hash) + getTimer();
      }
      if (hasPid()) {
        hash = (37 * hash) + PID_FIELD_NUMBER;
        hash = (53 * hash) + getPid();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestMessageProtos.Clock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProtos.Clock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProtos.Clock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProtos.Clock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProtos.Clock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.Clock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMessageProtos.Clock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.Clock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMessageProtos.Clock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.Clock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestMessageProtos.Clock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Clock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Clock)
        RequestMessageProtos.ClockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestMessageProtos.internal_static_Clock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestMessageProtos.internal_static_Clock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestMessageProtos.Clock.class, RequestMessageProtos.Clock.Builder.class);
      }

      // Construct using RequestMessageProtos.Clock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestMessageProtos.internal_static_Clock_descriptor;
      }

      public RequestMessageProtos.Clock getDefaultInstanceForType() {
        return RequestMessageProtos.Clock.getDefaultInstance();
      }

      public RequestMessageProtos.Clock build() {
        RequestMessageProtos.Clock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestMessageProtos.Clock buildPartial() {
        RequestMessageProtos.Clock result = new RequestMessageProtos.Clock(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timer_ = timer_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pid_ = pid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestMessageProtos.Clock) {
          return mergeFrom((RequestMessageProtos.Clock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestMessageProtos.Clock other) {
        if (other == RequestMessageProtos.Clock.getDefaultInstance()) return this;
        if (other.hasTimer()) {
          setTimer(other.getTimer());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimer()) {
          return false;
        }
        if (!hasPid()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestMessageProtos.Clock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestMessageProtos.Clock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timer_ ;
      /**
       * <code>required int32 timer = 1;</code>
       */
      public boolean hasTimer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 timer = 1;</code>
       */
      public int getTimer() {
        return timer_;
      }
      /**
       * <code>required int32 timer = 1;</code>
       */
      public Builder setTimer(int value) {
        bitField0_ |= 0x00000001;
        timer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 timer = 1;</code>
       */
      public Builder clearTimer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timer_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 2;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 pid = 2;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 2;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000002;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 2;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Clock)
    }

    // @@protoc_insertion_point(class_scope:Clock)
    private static final RequestMessageProtos.Clock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestMessageProtos.Clock();
    }

    public static RequestMessageProtos.Clock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Clock>
        PARSER = new com.google.protobuf.AbstractParser<Clock>() {
      public Clock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Clock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Clock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Clock> getParserForType() {
      return PARSER;
    }

    public RequestMessageProtos.Clock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VectorClockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VectorClock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    java.util.List<RequestMessageProtos.Clock> 
        getVectorClockList();
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    RequestMessageProtos.Clock getVectorClock(int index);
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    int getVectorClockCount();
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    java.util.List<? extends RequestMessageProtos.ClockOrBuilder> 
        getVectorClockOrBuilderList();
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    RequestMessageProtos.ClockOrBuilder getVectorClockOrBuilder(
        int index);

    /**
     * <code>required int32 rpid = 2;</code>
     */
    boolean hasRpid();
    /**
     * <code>required int32 rpid = 2;</code>
     */
    int getRpid();
  }
  /**
   * Protobuf type {@code VectorClock}
   */
  public  static final class VectorClock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VectorClock)
      VectorClockOrBuilder {
    // Use VectorClock.newBuilder() to construct.
    private VectorClock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VectorClock() {
      vectorClock_ = java.util.Collections.emptyList();
      rpid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VectorClock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vectorClock_ = new java.util.ArrayList<RequestMessageProtos.Clock>();
                mutable_bitField0_ |= 0x00000001;
              }
              vectorClock_.add(
                  input.readMessage(RequestMessageProtos.Clock.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              rpid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vectorClock_ = java.util.Collections.unmodifiableList(vectorClock_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestMessageProtos.internal_static_VectorClock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestMessageProtos.internal_static_VectorClock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestMessageProtos.VectorClock.class, RequestMessageProtos.VectorClock.Builder.class);
    }

    private int bitField0_;
    public static final int VECTOR_CLOCK_FIELD_NUMBER = 1;
    private java.util.List<RequestMessageProtos.Clock> vectorClock_;
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    public java.util.List<RequestMessageProtos.Clock> getVectorClockList() {
      return vectorClock_;
    }
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    public java.util.List<? extends RequestMessageProtos.ClockOrBuilder> 
        getVectorClockOrBuilderList() {
      return vectorClock_;
    }
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    public int getVectorClockCount() {
      return vectorClock_.size();
    }
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    public RequestMessageProtos.Clock getVectorClock(int index) {
      return vectorClock_.get(index);
    }
    /**
     * <code>repeated .Clock vector_clock = 1;</code>
     */
    public RequestMessageProtos.ClockOrBuilder getVectorClockOrBuilder(
        int index) {
      return vectorClock_.get(index);
    }

    public static final int RPID_FIELD_NUMBER = 2;
    private int rpid_;
    /**
     * <code>required int32 rpid = 2;</code>
     */
    public boolean hasRpid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rpid = 2;</code>
     */
    public int getRpid() {
      return rpid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRpid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getVectorClockCount(); i++) {
        if (!getVectorClock(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < vectorClock_.size(); i++) {
        output.writeMessage(1, vectorClock_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, rpid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < vectorClock_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, vectorClock_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rpid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestMessageProtos.VectorClock)) {
        return super.equals(obj);
      }
      RequestMessageProtos.VectorClock other = (RequestMessageProtos.VectorClock) obj;

      boolean result = true;
      result = result && getVectorClockList()
          .equals(other.getVectorClockList());
      result = result && (hasRpid() == other.hasRpid());
      if (hasRpid()) {
        result = result && (getRpid()
            == other.getRpid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getVectorClockCount() > 0) {
        hash = (37 * hash) + VECTOR_CLOCK_FIELD_NUMBER;
        hash = (53 * hash) + getVectorClockList().hashCode();
      }
      if (hasRpid()) {
        hash = (37 * hash) + RPID_FIELD_NUMBER;
        hash = (53 * hash) + getRpid();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestMessageProtos.VectorClock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProtos.VectorClock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProtos.VectorClock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProtos.VectorClock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProtos.VectorClock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.VectorClock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMessageProtos.VectorClock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.VectorClock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMessageProtos.VectorClock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.VectorClock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestMessageProtos.VectorClock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VectorClock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VectorClock)
        RequestMessageProtos.VectorClockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestMessageProtos.internal_static_VectorClock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestMessageProtos.internal_static_VectorClock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestMessageProtos.VectorClock.class, RequestMessageProtos.VectorClock.Builder.class);
      }

      // Construct using RequestMessageProtos.VectorClock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVectorClockFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (vectorClockBuilder_ == null) {
          vectorClock_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          vectorClockBuilder_.clear();
        }
        rpid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestMessageProtos.internal_static_VectorClock_descriptor;
      }

      public RequestMessageProtos.VectorClock getDefaultInstanceForType() {
        return RequestMessageProtos.VectorClock.getDefaultInstance();
      }

      public RequestMessageProtos.VectorClock build() {
        RequestMessageProtos.VectorClock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestMessageProtos.VectorClock buildPartial() {
        RequestMessageProtos.VectorClock result = new RequestMessageProtos.VectorClock(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (vectorClockBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            vectorClock_ = java.util.Collections.unmodifiableList(vectorClock_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.vectorClock_ = vectorClock_;
        } else {
          result.vectorClock_ = vectorClockBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rpid_ = rpid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestMessageProtos.VectorClock) {
          return mergeFrom((RequestMessageProtos.VectorClock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestMessageProtos.VectorClock other) {
        if (other == RequestMessageProtos.VectorClock.getDefaultInstance()) return this;
        if (vectorClockBuilder_ == null) {
          if (!other.vectorClock_.isEmpty()) {
            if (vectorClock_.isEmpty()) {
              vectorClock_ = other.vectorClock_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureVectorClockIsMutable();
              vectorClock_.addAll(other.vectorClock_);
            }
            onChanged();
          }
        } else {
          if (!other.vectorClock_.isEmpty()) {
            if (vectorClockBuilder_.isEmpty()) {
              vectorClockBuilder_.dispose();
              vectorClockBuilder_ = null;
              vectorClock_ = other.vectorClock_;
              bitField0_ = (bitField0_ & ~0x00000001);
              vectorClockBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getVectorClockFieldBuilder() : null;
            } else {
              vectorClockBuilder_.addAllMessages(other.vectorClock_);
            }
          }
        }
        if (other.hasRpid()) {
          setRpid(other.getRpid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRpid()) {
          return false;
        }
        for (int i = 0; i < getVectorClockCount(); i++) {
          if (!getVectorClock(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestMessageProtos.VectorClock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestMessageProtos.VectorClock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<RequestMessageProtos.Clock> vectorClock_ =
        java.util.Collections.emptyList();
      private void ensureVectorClockIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vectorClock_ = new java.util.ArrayList<RequestMessageProtos.Clock>(vectorClock_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          RequestMessageProtos.Clock, RequestMessageProtos.Clock.Builder, RequestMessageProtos.ClockOrBuilder> vectorClockBuilder_;

      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public java.util.List<RequestMessageProtos.Clock> getVectorClockList() {
        if (vectorClockBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vectorClock_);
        } else {
          return vectorClockBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public int getVectorClockCount() {
        if (vectorClockBuilder_ == null) {
          return vectorClock_.size();
        } else {
          return vectorClockBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public RequestMessageProtos.Clock getVectorClock(int index) {
        if (vectorClockBuilder_ == null) {
          return vectorClock_.get(index);
        } else {
          return vectorClockBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder setVectorClock(
          int index, RequestMessageProtos.Clock value) {
        if (vectorClockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorClockIsMutable();
          vectorClock_.set(index, value);
          onChanged();
        } else {
          vectorClockBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder setVectorClock(
          int index, RequestMessageProtos.Clock.Builder builderForValue) {
        if (vectorClockBuilder_ == null) {
          ensureVectorClockIsMutable();
          vectorClock_.set(index, builderForValue.build());
          onChanged();
        } else {
          vectorClockBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder addVectorClock(RequestMessageProtos.Clock value) {
        if (vectorClockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorClockIsMutable();
          vectorClock_.add(value);
          onChanged();
        } else {
          vectorClockBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder addVectorClock(
          int index, RequestMessageProtos.Clock value) {
        if (vectorClockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorClockIsMutable();
          vectorClock_.add(index, value);
          onChanged();
        } else {
          vectorClockBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder addVectorClock(
          RequestMessageProtos.Clock.Builder builderForValue) {
        if (vectorClockBuilder_ == null) {
          ensureVectorClockIsMutable();
          vectorClock_.add(builderForValue.build());
          onChanged();
        } else {
          vectorClockBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder addVectorClock(
          int index, RequestMessageProtos.Clock.Builder builderForValue) {
        if (vectorClockBuilder_ == null) {
          ensureVectorClockIsMutable();
          vectorClock_.add(index, builderForValue.build());
          onChanged();
        } else {
          vectorClockBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder addAllVectorClock(
          java.lang.Iterable<? extends RequestMessageProtos.Clock> values) {
        if (vectorClockBuilder_ == null) {
          ensureVectorClockIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, vectorClock_);
          onChanged();
        } else {
          vectorClockBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder clearVectorClock() {
        if (vectorClockBuilder_ == null) {
          vectorClock_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          vectorClockBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public Builder removeVectorClock(int index) {
        if (vectorClockBuilder_ == null) {
          ensureVectorClockIsMutable();
          vectorClock_.remove(index);
          onChanged();
        } else {
          vectorClockBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public RequestMessageProtos.Clock.Builder getVectorClockBuilder(
          int index) {
        return getVectorClockFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public RequestMessageProtos.ClockOrBuilder getVectorClockOrBuilder(
          int index) {
        if (vectorClockBuilder_ == null) {
          return vectorClock_.get(index);  } else {
          return vectorClockBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public java.util.List<? extends RequestMessageProtos.ClockOrBuilder> 
           getVectorClockOrBuilderList() {
        if (vectorClockBuilder_ != null) {
          return vectorClockBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vectorClock_);
        }
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public RequestMessageProtos.Clock.Builder addVectorClockBuilder() {
        return getVectorClockFieldBuilder().addBuilder(
            RequestMessageProtos.Clock.getDefaultInstance());
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public RequestMessageProtos.Clock.Builder addVectorClockBuilder(
          int index) {
        return getVectorClockFieldBuilder().addBuilder(
            index, RequestMessageProtos.Clock.getDefaultInstance());
      }
      /**
       * <code>repeated .Clock vector_clock = 1;</code>
       */
      public java.util.List<RequestMessageProtos.Clock.Builder> 
           getVectorClockBuilderList() {
        return getVectorClockFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          RequestMessageProtos.Clock, RequestMessageProtos.Clock.Builder, RequestMessageProtos.ClockOrBuilder> 
          getVectorClockFieldBuilder() {
        if (vectorClockBuilder_ == null) {
          vectorClockBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              RequestMessageProtos.Clock, RequestMessageProtos.Clock.Builder, RequestMessageProtos.ClockOrBuilder>(
                  vectorClock_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          vectorClock_ = null;
        }
        return vectorClockBuilder_;
      }

      private int rpid_ ;
      /**
       * <code>required int32 rpid = 2;</code>
       */
      public boolean hasRpid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 rpid = 2;</code>
       */
      public int getRpid() {
        return rpid_;
      }
      /**
       * <code>required int32 rpid = 2;</code>
       */
      public Builder setRpid(int value) {
        bitField0_ |= 0x00000002;
        rpid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rpid = 2;</code>
       */
      public Builder clearRpid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rpid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VectorClock)
    }

    // @@protoc_insertion_point(class_scope:VectorClock)
    private static final RequestMessageProtos.VectorClock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestMessageProtos.VectorClock();
    }

    public static RequestMessageProtos.VectorClock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VectorClock>
        PARSER = new com.google.protobuf.AbstractParser<VectorClock>() {
      public VectorClock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new VectorClock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VectorClock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VectorClock> getParserForType() {
      return PARSER;
    }

    public RequestMessageProtos.VectorClock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AcknowledgementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Acknowledgement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *#actually sending ok
     * </pre>
     *
     * <code>optional bool ok = 1;</code>
     */
    boolean hasOk();
    /**
     * <pre>
     *#actually sending ok
     * </pre>
     *
     * <code>optional bool ok = 1;</code>
     */
    boolean getOk();

    /**
     * <pre>
     *#just for the sake of sending
     * </pre>
     *
     * <code>optional bool queued_ok = 2;</code>
     */
    boolean hasQueuedOk();
    /**
     * <pre>
     *#just for the sake of sending
     * </pre>
     *
     * <code>optional bool queued_ok = 2;</code>
     */
    boolean getQueuedOk();

    /**
     * <code>required .VectorClock sender_clock = 3;</code>
     */
    boolean hasSenderClock();
    /**
     * <code>required .VectorClock sender_clock = 3;</code>
     */
    RequestMessageProtos.VectorClock getSenderClock();
    /**
     * <code>required .VectorClock sender_clock = 3;</code>
     */
    RequestMessageProtos.VectorClockOrBuilder getSenderClockOrBuilder();
  }
  /**
   * Protobuf type {@code Acknowledgement}
   */
  public  static final class Acknowledgement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Acknowledgement)
      AcknowledgementOrBuilder {
    // Use Acknowledgement.newBuilder() to construct.
    private Acknowledgement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Acknowledgement() {
      ok_ = false;
      queuedOk_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Acknowledgement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ok_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              queuedOk_ = input.readBool();
              break;
            }
            case 26: {
              RequestMessageProtos.VectorClock.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = senderClock_.toBuilder();
              }
              senderClock_ = input.readMessage(RequestMessageProtos.VectorClock.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(senderClock_);
                senderClock_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestMessageProtos.internal_static_Acknowledgement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestMessageProtos.internal_static_Acknowledgement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestMessageProtos.Acknowledgement.class, RequestMessageProtos.Acknowledgement.Builder.class);
    }

    private int bitField0_;
    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <pre>
     *#actually sending ok
     * </pre>
     *
     * <code>optional bool ok = 1;</code>
     */
    public boolean hasOk() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *#actually sending ok
     * </pre>
     *
     * <code>optional bool ok = 1;</code>
     */
    public boolean getOk() {
      return ok_;
    }

    public static final int QUEUED_OK_FIELD_NUMBER = 2;
    private boolean queuedOk_;
    /**
     * <pre>
     *#just for the sake of sending
     * </pre>
     *
     * <code>optional bool queued_ok = 2;</code>
     */
    public boolean hasQueuedOk() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *#just for the sake of sending
     * </pre>
     *
     * <code>optional bool queued_ok = 2;</code>
     */
    public boolean getQueuedOk() {
      return queuedOk_;
    }

    public static final int SENDER_CLOCK_FIELD_NUMBER = 3;
    private RequestMessageProtos.VectorClock senderClock_;
    /**
     * <code>required .VectorClock sender_clock = 3;</code>
     */
    public boolean hasSenderClock() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .VectorClock sender_clock = 3;</code>
     */
    public RequestMessageProtos.VectorClock getSenderClock() {
      return senderClock_ == null ? RequestMessageProtos.VectorClock.getDefaultInstance() : senderClock_;
    }
    /**
     * <code>required .VectorClock sender_clock = 3;</code>
     */
    public RequestMessageProtos.VectorClockOrBuilder getSenderClockOrBuilder() {
      return senderClock_ == null ? RequestMessageProtos.VectorClock.getDefaultInstance() : senderClock_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSenderClock()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSenderClock().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, ok_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, queuedOk_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getSenderClock());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, queuedOk_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSenderClock());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestMessageProtos.Acknowledgement)) {
        return super.equals(obj);
      }
      RequestMessageProtos.Acknowledgement other = (RequestMessageProtos.Acknowledgement) obj;

      boolean result = true;
      result = result && (hasOk() == other.hasOk());
      if (hasOk()) {
        result = result && (getOk()
            == other.getOk());
      }
      result = result && (hasQueuedOk() == other.hasQueuedOk());
      if (hasQueuedOk()) {
        result = result && (getQueuedOk()
            == other.getQueuedOk());
      }
      result = result && (hasSenderClock() == other.hasSenderClock());
      if (hasSenderClock()) {
        result = result && getSenderClock()
            .equals(other.getSenderClock());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasOk()) {
        hash = (37 * hash) + OK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getOk());
      }
      if (hasQueuedOk()) {
        hash = (37 * hash) + QUEUED_OK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getQueuedOk());
      }
      if (hasSenderClock()) {
        hash = (37 * hash) + SENDER_CLOCK_FIELD_NUMBER;
        hash = (53 * hash) + getSenderClock().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestMessageProtos.Acknowledgement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProtos.Acknowledgement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProtos.Acknowledgement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProtos.Acknowledgement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProtos.Acknowledgement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.Acknowledgement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMessageProtos.Acknowledgement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.Acknowledgement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMessageProtos.Acknowledgement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMessageProtos.Acknowledgement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestMessageProtos.Acknowledgement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Acknowledgement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Acknowledgement)
        RequestMessageProtos.AcknowledgementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestMessageProtos.internal_static_Acknowledgement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestMessageProtos.internal_static_Acknowledgement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestMessageProtos.Acknowledgement.class, RequestMessageProtos.Acknowledgement.Builder.class);
      }

      // Construct using RequestMessageProtos.Acknowledgement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSenderClockFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        ok_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        queuedOk_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (senderClockBuilder_ == null) {
          senderClock_ = null;
        } else {
          senderClockBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestMessageProtos.internal_static_Acknowledgement_descriptor;
      }

      public RequestMessageProtos.Acknowledgement getDefaultInstanceForType() {
        return RequestMessageProtos.Acknowledgement.getDefaultInstance();
      }

      public RequestMessageProtos.Acknowledgement build() {
        RequestMessageProtos.Acknowledgement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestMessageProtos.Acknowledgement buildPartial() {
        RequestMessageProtos.Acknowledgement result = new RequestMessageProtos.Acknowledgement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ok_ = ok_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.queuedOk_ = queuedOk_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (senderClockBuilder_ == null) {
          result.senderClock_ = senderClock_;
        } else {
          result.senderClock_ = senderClockBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestMessageProtos.Acknowledgement) {
          return mergeFrom((RequestMessageProtos.Acknowledgement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestMessageProtos.Acknowledgement other) {
        if (other == RequestMessageProtos.Acknowledgement.getDefaultInstance()) return this;
        if (other.hasOk()) {
          setOk(other.getOk());
        }
        if (other.hasQueuedOk()) {
          setQueuedOk(other.getQueuedOk());
        }
        if (other.hasSenderClock()) {
          mergeSenderClock(other.getSenderClock());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSenderClock()) {
          return false;
        }
        if (!getSenderClock().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestMessageProtos.Acknowledgement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestMessageProtos.Acknowledgement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean ok_ ;
      /**
       * <pre>
       *#actually sending ok
       * </pre>
       *
       * <code>optional bool ok = 1;</code>
       */
      public boolean hasOk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *#actually sending ok
       * </pre>
       *
       * <code>optional bool ok = 1;</code>
       */
      public boolean getOk() {
        return ok_;
      }
      /**
       * <pre>
       *#actually sending ok
       * </pre>
       *
       * <code>optional bool ok = 1;</code>
       */
      public Builder setOk(boolean value) {
        bitField0_ |= 0x00000001;
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *#actually sending ok
       * </pre>
       *
       * <code>optional bool ok = 1;</code>
       */
      public Builder clearOk() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ok_ = false;
        onChanged();
        return this;
      }

      private boolean queuedOk_ ;
      /**
       * <pre>
       *#just for the sake of sending
       * </pre>
       *
       * <code>optional bool queued_ok = 2;</code>
       */
      public boolean hasQueuedOk() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *#just for the sake of sending
       * </pre>
       *
       * <code>optional bool queued_ok = 2;</code>
       */
      public boolean getQueuedOk() {
        return queuedOk_;
      }
      /**
       * <pre>
       *#just for the sake of sending
       * </pre>
       *
       * <code>optional bool queued_ok = 2;</code>
       */
      public Builder setQueuedOk(boolean value) {
        bitField0_ |= 0x00000002;
        queuedOk_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *#just for the sake of sending
       * </pre>
       *
       * <code>optional bool queued_ok = 2;</code>
       */
      public Builder clearQueuedOk() {
        bitField0_ = (bitField0_ & ~0x00000002);
        queuedOk_ = false;
        onChanged();
        return this;
      }

      private RequestMessageProtos.VectorClock senderClock_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          RequestMessageProtos.VectorClock, RequestMessageProtos.VectorClock.Builder, RequestMessageProtos.VectorClockOrBuilder> senderClockBuilder_;
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      public boolean hasSenderClock() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      public RequestMessageProtos.VectorClock getSenderClock() {
        if (senderClockBuilder_ == null) {
          return senderClock_ == null ? RequestMessageProtos.VectorClock.getDefaultInstance() : senderClock_;
        } else {
          return senderClockBuilder_.getMessage();
        }
      }
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      public Builder setSenderClock(RequestMessageProtos.VectorClock value) {
        if (senderClockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          senderClock_ = value;
          onChanged();
        } else {
          senderClockBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      public Builder setSenderClock(
          RequestMessageProtos.VectorClock.Builder builderForValue) {
        if (senderClockBuilder_ == null) {
          senderClock_ = builderForValue.build();
          onChanged();
        } else {
          senderClockBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      public Builder mergeSenderClock(RequestMessageProtos.VectorClock value) {
        if (senderClockBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              senderClock_ != null &&
              senderClock_ != RequestMessageProtos.VectorClock.getDefaultInstance()) {
            senderClock_ =
              RequestMessageProtos.VectorClock.newBuilder(senderClock_).mergeFrom(value).buildPartial();
          } else {
            senderClock_ = value;
          }
          onChanged();
        } else {
          senderClockBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      public Builder clearSenderClock() {
        if (senderClockBuilder_ == null) {
          senderClock_ = null;
          onChanged();
        } else {
          senderClockBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      public RequestMessageProtos.VectorClock.Builder getSenderClockBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSenderClockFieldBuilder().getBuilder();
      }
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      public RequestMessageProtos.VectorClockOrBuilder getSenderClockOrBuilder() {
        if (senderClockBuilder_ != null) {
          return senderClockBuilder_.getMessageOrBuilder();
        } else {
          return senderClock_ == null ?
              RequestMessageProtos.VectorClock.getDefaultInstance() : senderClock_;
        }
      }
      /**
       * <code>required .VectorClock sender_clock = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RequestMessageProtos.VectorClock, RequestMessageProtos.VectorClock.Builder, RequestMessageProtos.VectorClockOrBuilder> 
          getSenderClockFieldBuilder() {
        if (senderClockBuilder_ == null) {
          senderClockBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RequestMessageProtos.VectorClock, RequestMessageProtos.VectorClock.Builder, RequestMessageProtos.VectorClockOrBuilder>(
                  getSenderClock(),
                  getParentForChildren(),
                  isClean());
          senderClock_ = null;
        }
        return senderClockBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Acknowledgement)
    }

    // @@protoc_insertion_point(class_scope:Acknowledgement)
    private static final RequestMessageProtos.Acknowledgement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestMessageProtos.Acknowledgement();
    }

    public static RequestMessageProtos.Acknowledgement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Acknowledgement>
        PARSER = new com.google.protobuf.AbstractParser<Acknowledgement>() {
      public Acknowledgement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Acknowledgement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Acknowledgement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Acknowledgement> getParserForType() {
      return PARSER;
    }

    public RequestMessageProtos.Acknowledgement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Clock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Clock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VectorClock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VectorClock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Acknowledgement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Acknowledgement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025request_message.proto\"#\n\005Clock\022\r\n\005time" +
      "r\030\001 \002(\005\022\013\n\003pid\030\002 \002(\005\"9\n\013VectorClock\022\034\n\014v" +
      "ector_clock\030\001 \003(\0132\006.Clock\022\014\n\004rpid\030\002 \002(\005\"" +
      "T\n\017Acknowledgement\022\n\n\002ok\030\001 \001(\010\022\021\n\tqueued" +
      "_ok\030\002 \001(\010\022\"\n\014sender_clock\030\003 \002(\0132\014.Vector" +
      "ClockB\026B\024RequestMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Clock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Clock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Clock_descriptor,
        new java.lang.String[] { "Timer", "Pid", });
    internal_static_VectorClock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VectorClock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VectorClock_descriptor,
        new java.lang.String[] { "VectorClock", "Rpid", });
    internal_static_Acknowledgement_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Acknowledgement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Acknowledgement_descriptor,
        new java.lang.String[] { "Ok", "QueuedOk", "SenderClock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
